[phases.setup]
nixPkgs = ["nodejs-20_x", "npm-10_x"]

[phases.install]
cmds = [
    "npm ci --include=dev"
]

[phases.build]
cmds = [
    "npm run build:production"
]

[start]
cmd = "npm run preview"

[variables]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false"

[build]
# Configuração específica para resolver o problema do NIXPACKS_PATH
env = ["NIXPACKS_PATH=/app/node_modules/.bin:$PATH"]

[providers]
# Usa o provider do Node.js
nodejs = {} 